"""Reproduce the frozen T48M export and generate its DSP header candidates."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import subprocess

import numpy as np
from scipy.signal import firwin

import numeric as N


def log_filterbank(n_fft, bpo):
    """Unique nearest-bin triangular filters, normalized before float32 storage."""
    lo = math.floor(bpo * math.log2(30.0 / 440.0))
    hi = math.ceil(bpo * math.log2(11000.0 / 440.0))
    frequencies = 440.0 * 2.0 ** (np.arange(lo, hi + 1) / bpo)
    frequencies = frequencies[(frequencies >= 30.0) & (frequencies <= 11000.0)]
    bins = np.unique(np.clip(np.rint(frequencies / (N.SR / n_fft)).astype(int), 0, n_fft // 2))
    bands = []
    for start, centre, stop in zip(bins[:-2], bins[1:-1], bins[2:]):
        values = np.zeros(stop - start - 1, np.float64)
        for j in range(start + 1, centre):
            values[j - start - 1] = (j - start) / (centre - start)
        values[centre - start - 1] = 1.0
        for j in range(centre + 1, stop):
            values[j - start - 1] = (stop - j) / (stop - centre)
        bands.append((start + 1, (values / values.sum()).astype(np.float32)))
    return bands


def frontend_tables(window_device):
    import torch
    tables, weights, groups = {}, [], [0]
    for n, bpo in zip((512, 1024, 2048), (6, 12, 24)):
        tables[f"hann{n}"] = torch.hann_window(n, periodic=False, device=window_device).cpu().numpy()
        bands = []
        for first, values in log_filterbank(n, bpo):
            bands.append((first, len(values), len(weights)))
            weights.extend(values)
        tables[f"bands{n}"] = np.asarray(bands, np.int64)
        groups.append(groups[-1] + len(bands))
    tables["weights"] = np.asarray(weights, np.float32)
    tables["groups"] = np.asarray(groups, np.int64)
    for rate in (48000, 96000, 192000):
        factor = rate // N.SR
        tables[f"fir{rate // 1000}"] = firwin(32 * factor + 1, .94 / factor, window=("kaiser", 8.6))
    assert groups[-1] * 2 == N.INPUTS
    return tables


def cpp_array(name, values, dtype):
    flat = np.asarray(values).reshape(-1)
    if dtype == "std::uint16_t":
        entries = [f"0x{int(v):04x}u" for v in flat]
    elif dtype == "float":
        entries = [float(v).hex() + "f" for v in flat]
    else:
        entries = [float(v).hex() for v in flat]
    rows = ["    " + ", ".join(entries[i:i + 8]) + "," for i in range(0, len(entries), 8)]
    return f"inline constexpr {dtype} {name}[{len(flat)}] = {{\n" + "\n".join(rows) + "\n};\n"


def weight_header(tensors):
    content = ["// T48M, generated by tools/rhythm-analyzer/export.py.\n"
               "// Weights: binary16 RNE; input normalization: float32.\n"
               "// Layout: input[c][o], conv[layer][c][tap][o], output[c][o].\n"
               "#pragma once\n#include <cstdint>\n\n"
               "namespace effetune::plugins::analyzer::rhythm_a3::tc {\n\n",
               f'inline constexpr char kTcnExportSha256[] = "{N.MODEL_SHA256}";\n']
    for name, key in (("kTcnMu", "mu"), ("kTcnSd", "sd")):
        content.append(cpp_array(name, tensors[key], "float"))
    arrays = {
        "kTcnInpW": tensors["inp.weight"].T,
        "kTcnInpB": tensors["inp.bias"],
        "kTcnConvW": np.stack([tensors[f"convs.{l}.weight"].transpose(1, 2, 0) for l in range(N.LAYERS)]),
        "kTcnConvB": np.stack([tensors[f"convs.{l}.bias"] for l in range(N.LAYERS)]),
        "kTcnOutW": tensors["out.weight"].T,
        "kTcnOutB": tensors["out.bias"],
    }
    content.extend(cpp_array(name, values, "std::uint16_t") for name, values in arrays.items())
    content.append("\n} // namespace effetune::plugins::analyzer::rhythm_a3::tc\n")
    return "\n".join(content)


def frontend_header(tables):
    content = ["// Generated by tools/rhythm-analyzer/export.py. See tc_constants.provenance.json.\n"
               "#pragma once\n#include <cstdint>\n\n"
               "namespace effetune::plugins::analyzer::rhythm_a3::tc {\n\n"
               "struct FilterBand { std::uint16_t first, count; std::uint32_t offset; };\n"]
    for n in (512, 1024, 2048):
        content.append(cpp_array(f"kHann{n}", tables[f"hann{n}"], "float"))
    content.append(cpp_array("kFilterWeights", tables["weights"], "float"))
    content.append("inline constexpr FilterBand kFilterBands[250] = {\n")
    for n in (512, 1024, 2048):
        content.extend(f"    {{{first}u, {count}u, {offset}u}},\n" for first, count, offset in tables[f"bands{n}"])
    content.append("};\n")
    content.append("inline constexpr std::uint32_t kGroupOffsets[4] = {" +
                   ", ".join(f"{v}u" for v in tables["groups"]) + "};\n")
    for rate in (48, 96, 192):
        content.append(cpp_array(f"kFir{rate}", tables[f"fir{rate}"], "double"))
    content.append("\n} // namespace effetune::plugins::analyzer::rhythm_a3::tc\n")
    return "\n".join(content)


def checkpoint_export(path):
    import torch
    state = torch.load(path, map_location="cpu", weights_only=True)
    if state["step"] != 17500 or state["cfg"]["seed"] != 0 or state["cfg"]["tag"] != "t48M":
        raise ValueError("The checkpoint is not the frozen T48M seed 0, step 17500 model.")
    parts = []
    for name, shape, dtype in N.tensor_layout():
        values = state["net"][name].cpu().numpy().astype(np.float32)
        if values.shape != shape or not np.isfinite(values).all():
            raise ValueError(f"Invalid tensor {name}.")
        if name == "sd" and np.any(values <= 0):
            raise ValueError("Input standard deviations must be positive.")
        data = values.astype("<f4") if dtype == "<f4" else N.encode_half(values).astype("<u2")
        if dtype == "<u2" and np.any((data & 0x7c00) == 0x7c00):
            raise ValueError(f"Non-finite binary16 export in {name}.")
        parts.append(data.tobytes(order="C"))
    blob = b"".join(parts)
    if len(blob) != N.MODEL_BYTES or hashlib.sha256(blob).hexdigest() != N.MODEL_SHA256:
        raise ValueError("The export differs from the frozen T48M artifact.")
    return blob


def write_text(path, content):
    path.write_text(content, encoding="utf-8", newline="\n")


def format_header(content, filename, executable):
    if executable is None:
        return content
    assumed_path = Path(__file__).resolve().parents[2] / "dsp/plugins/analyzer/rhythm_analyzer" / filename
    result = subprocess.run([str(executable), "--style=file", f"--assume-filename={assumed_path}"],
                            input=content, text=True, encoding="utf-8", capture_output=True, check=True)
    return result.stdout.replace("\r\n", "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--checkpoint", type=Path, help="Trusted frozen training checkpoint")
    source.add_argument("--model", type=Path, help="Frozen binary export")
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--window-device", choices=("cpu", "cuda"), default="cuda",
                        help="Frozen export uses CUDA Hann coefficients; CPU is a comparison variant")
    parser.add_argument("--clang-format", type=Path, help="Compatible clang-format executable; hashes are recorded after formatting")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    if args.checkpoint:
        blob = checkpoint_export(args.checkpoint)
        (args.out / "t48M.fp16.bin").write_bytes(blob)
        model = args.out / "t48M.fp16.bin"
    else:
        model = args.model
    tensors = N.read_model(model)
    header = format_header(weight_header(tensors), "tc_tcn_weights.h", args.clang_format)
    write_text(args.out / "tc_tcn_weights.h", header)
    tables = frontend_tables(args.window_device)
    np.savez_compressed(args.out / "frontend.npz", **tables)
    fe_header = format_header(frontend_header(tables), "tc_constants.h", args.clang_format)
    write_text(args.out / "tc_constants.h", fe_header)
    provenance = {
        "artifact": "tc_tcn_weights.h", "export_sha256": N.MODEL_SHA256,
        "header_sha256": hashlib.sha256(header.encode()).hexdigest(),
        "model": "T48M", "selection": "Frozen seed 0, checkpoint step 17500; no implementation retuning",
        "ruling": "R6-S-27", "network_bytes": N.MODEL_BYTES,
        "learned_half_count": 131247, "learned_half_bytes": 262494, "normalization_float32_bytes": 4000,
        "architecture": {"inputs": 500, "channels": 48, "layers": 9, "taps": 5,
                         "dilations": [1 << i for i in range(9)], "heads": ["beat", "downbeat", "tempo (61)"]},
        "numerics": "fp32 ordered multiply then add, FMA disabled; binary16 weights and per-layer input rings; integer RNE half conversion",
        "training_recipe": "Frame-proportional sampling within each set; set shares proportional to the square root of training duration; causal crops with tempo, pitch, gain and tilt augmentation",
        "training_datasets": ["Ballroom", "BRID", "Candombe", "Groove MIDI", "GuitarSet",
                              "MusicNet public-domain recordings", "Salsa", "Slakh2100-redux validation",
                              "Schubert Winterreise public-domain recordings"],
        "runtime_decision": "Fixed weights compiled into the DSP; no runtime training or adaptation",
        "generator": "tools/rhythm-analyzer/export.py"
    }
    write_text(args.out / "tc_tcn_weights.provenance.json", json.dumps(provenance, indent=2) + "\n")
    import scipy
    import torch
    fe_provenance = {
        "artifact": "tc_constants.h", "generator": "tools/rhythm-analyzer/export.py",
        "header_sha256": hashlib.sha256(fe_header.encode()).hexdigest(),
        "method": "Non-periodic Hann; nearest-bin unique triangular logarithmic filters normalized to sum one; beat FIR firwin(32*factor+1, .94/factor, Kaiser beta 8.6)",
        "frames": [512, 1024, 2048], "bands_per_octave": [6, 12, 24], "group_offsets": tables["groups"].tolist(),
        "sample_rate": N.SR, "hop": N.HOP, "fmin": 30, "fmax": 11000,
        "window_generator": f"torch {torch.__version__} hann_window(periodic=False, device={args.window_device})",
        "fir_generator": f"scipy {scipy.__version__} firwin",
        "derived_constants_bytes": (sum(tables[f"hann{n}"].nbytes for n in (512, 1024, 2048)) +
                                    tables["weights"].nbytes + 250 * 8 + 4 * 4 +
                                    sum(tables[f"fir{rate}"].nbytes for rate in (48, 96, 192))),
        "classification": "Derived constants, not learned parameters"
    }
    write_text(args.out / "tc_constants.provenance.json", json.dumps(fe_provenance, indent=2) + "\n")
    print(json.dumps({"model_bytes": N.MODEL_BYTES, "sha256": N.MODEL_SHA256,
                      "frontend_groups": tables["groups"].tolist(), "window_device": args.window_device}))


if __name__ == "__main__":
    main()
