"""Validate and embed the Note Spectrogram's immutable binary tree models."""

import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import struct


def read_model(manifest_path):
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    name = manifest_path.stem
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        raise ValueError("Invalid model name")
    if manifest["formatVersion"] != 1:
        raise ValueError("Unsupported model format")
    constants = manifest["constants"]
    for key, value in constants.items():
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", key) or not math.isfinite(value):
            raise ValueError("Invalid model constant")
    for key in ("FeatureCount", "TreeCount", "Depth"):
        if type(constants[key]) is not int or constants[key] <= 0:
            raise ValueError(f"Invalid {key}")
    if constants["FeatureCount"] > 256 or constants["Depth"] > 16:
        raise ValueError("Unsupported feature count or tree depth")
    if manifest["outputCount"] not in (1, 4):
        raise ValueError("Unsupported output count")
    leaf_type = manifest["leafType"]
    if leaf_type not in ("float", "double"):
        raise ValueError("Unsupported leaf type")
    trees, depth = constants["TreeCount"], constants["Depth"]
    splits = trees * ((1 << depth) - 1)
    leaves = trees * (1 << depth) * manifest["outputCount"]
    arrays = []
    offset = 0
    for suffix, kind, count, width in (
        ("features", "std::uint8_t", splits, 1),
        ("thresholds", "float", splits, 4),
        ("leaves", leaf_type, leaves, 4 if leaf_type == "float" else 8),
    ):
        offset = (offset + width - 1) // width * width
        arrays.append((f"et_note_{name}_{suffix}", kind, count, offset, count * width))
        offset += count * width
    binary_path = manifest_path.with_suffix(".bin")
    data = binary_path.read_bytes()
    if len(data) != offset:
        raise ValueError("Model byte count does not match its dimensions")
    if hashlib.sha256(data).hexdigest() != manifest["sha256"]:
        raise ValueError("Model SHA-256 mismatch")
    if max(data[:splits]) >= constants["FeatureCount"]:
        raise ValueError("Model contains a forbidden feature split")
    for _, kind, _, offset, size in arrays[1:]:
        for (value,) in struct.iter_unpack("<f" if kind == "float" else "<d",
                                          data[offset:offset + size]):
            if not math.isfinite(value):
                raise ValueError("Model contains a non-finite value")
    return name, manifest, arrays, data


def model_header(name, manifest, arrays):
    lines = [
        "// Generated by embed_models.py; do not edit.",
        "#pragma once", '#include "heap_tree_model.h"',
        "#include <bit>", "#include <limits>",
        "static_assert(std::endian::native == std::endian::little);",
        "static_assert(sizeof(float) == 4 && std::numeric_limits<float>::is_iec559);",
        "static_assert(sizeof(double) == 8 && std::numeric_limits<double>::is_iec559);",
        f"namespace effetune::plugins::analyzer::{name} {{",
    ]
    for key, value in manifest["constants"].items():
        kind = "std::uint32_t" if type(value) is int else "double"
        literal = f"{value}u" if type(value) is int else float(value).hex()
        lines.append(f"inline constexpr {kind} k{key} = {literal};")
    for symbol, kind, count, _, _ in arrays:
        lines.append(f'extern "C" const {kind} {symbol}[{count}];')
    view = "FloatHeapTreeModelView" if manifest["leafType"] == "float" else "HeapTreeModelView"
    lines.extend([
        f"inline constexpr {view} model() noexcept {{",
        "  return {kFeatureCount, kTreeCount, kDepth, kScale, kBias,",
        "          " + ", ".join(a[0] for a in arrays) + "};",
        "}", "}", "",
    ])
    return "\n".join(lines)


def model_assembly(binary_path, arrays, target):
    # Each typed array is a separate aligned symbol; no runtime decoding or copying.
    path = binary_path.resolve().as_posix().replace('"', '\\"')
    lines = []
    for symbol, _, _, offset, size in arrays:
        if target == "macho":
            symbol = "_" + symbol
            lines.extend([".section __TEXT,__const", f".private_extern {symbol}"])
        else:
            section_type = "" if target == "wasm" else "progbits"
            flags = "a" if target == "elf" else ""
            lines.extend([f'.section .rodata.{symbol},"{flags}",@{section_type}',
                          f".hidden {symbol}", f".type {symbol},@object"])
        lines.extend([f".globl {symbol}", ".p2align 3", f"{symbol}:",
                      f'.incbin "{path}", {offset}, {size}'])
        if target != "macho":
            lines.append(f".size {symbol}, {size}")
    if target == "elf":
        lines.append('.section .note.GNU-stack,"",@progbits')
    return "\n".join(lines) + "\n"


def model_coff(arrays, data, machine):
    # MSVC has no .incbin. Emit a relocation-free COFF data object instead.
    # https://learn.microsoft.com/en-us/windows/win32/debug/pe-format
    strings = bytearray()
    symbols = bytearray()
    for symbol, _, _, offset, _ in arrays:
        symbols.extend(struct.pack("<IIIhHBB", 0, 4 + len(strings), offset, 1, 0, 2, 0))
        strings.extend(symbol.encode("ascii") + b"\0")
    header = struct.pack("<HHIIIHH", machine, 1, 0, 60 + len(data), len(arrays), 0, 0)
    # One initialized, read-only section aligned to eight bytes; no relocations.
    section = struct.pack("<8sIIIIIIHHI", b".rdata", 0, 0, len(data), 60,
                          0, 0, 0, 0, 0x40400040)
    return header + section + data + symbols + struct.pack("<I", 4 + len(strings)) + strings


def embed_model(manifest_path, output_dir, target):
    name, manifest, arrays, data = read_model(manifest_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    header = output_dir / f"{name}.generated.h"
    header.write_text(model_header(name, manifest, arrays), encoding="utf-8", newline="\n")
    if target.startswith("coff-"):
        machine = {"coff-x64": 0x8664, "coff-arm64": 0xAA64}[target]
        (output_dir / f"{name}.obj").write_bytes(model_coff(arrays, data, machine))
    else:
        (output_dir / f"{name}.S").write_text(
            model_assembly(manifest_path.with_suffix(".bin"), arrays, target),
            encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--target", choices=("elf", "macho", "wasm", "coff-x64", "coff-arm64"),
                        required=True)
    arguments = parser.parse_args()
    embed_model(arguments.manifest, arguments.output_dir, arguments.target)
