# Generated by scripts/gen-dsp-library-bindings.mjs. Do not edit.

GRAPH_V1_CAPACITY = {
  'maxStructuralNodes': 128,
  'maxEffectiveInstances': 96,
  'maxEdges': 512,
  'maxLiveBuffers': 129,
  'maxWorkspaceBytes': 67108864
}
